export const GET_COURSE_LIST_REQUEST = 'GET_COURSE_LIST_REQUEST';
export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS';
export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const GET_COURSE_BY_ID_REQUEST = 'GET_COURSE_BY_ID_REQUEST';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const EDIT_COURSE_REQUEST = 'EDIT_COURSE_REQUEST';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
